stages:
  - lint
  - test
  - deploy

lint-server:
  stage: lint
  image: node:latest
  script:
    - cd server
    - npm install
    - npm run lint
    - npm run format
  artifacts:
    paths:
      - server/node_modules

lint-client:
  stage: lint
  image: node:latest
  script:
    - cd client
    - npm install
    - npm run lint
    - npm run format
  artifacts:
    paths:
      - client/node_modules

test-server:
  stage: test
  image: node:latest
  script:
    - cd server
    - npm install
    - npm run test:coverage
  artifacts:
    paths:
      - server/node_modules
      - server/coverage

deploy-coverage-server:
  stage: deploy
  image: alpine
  dependencies:
    - test-server
  script:
    - apk add --no-cache git
    - git clone $CI_PROJECT_URL deploy
    - rm -rf deploy/*
    - cp -r ./server/coverage/lcov-report/* deploy/
    - cd deploy
    - git config user.name "GitLab CI"
    - git config user.email "gitlab-ci@etu.univ-lyon1.fr"
    - git add -A
    - git commit -m "Deploy code coverage report"
    - git push origin main
  only:
    - main

