stages:
  - lint
  - test

lint-server:
  stage: lint
  image: node:latest
  script:
    - cd server
    - npm install
    - npm run lint
    - npm run format
  artifacts:
    paths:
      - server/node_modules

lint-client:
  stage: lint
  image: node:latest
  script:
    - cd client
    - npm install
    - npm run lint
    - npm run format
  artifacts:
    paths:
      - client/node_modules

test-server:
  stage: test
  image: node:latest
  script:
    - cd server
    - npm install
    - npm run test:coverage
  artifacts:
    paths:
      - server/node_modules
      - server/coverage
